import type {
  BatchDefinition,
  BatchStatus,
  Criticality,
} from "@batchtrail/domain";

export type BatchRegistrationFormValues = {
  batchId: string;
  name: string;
  owner: string;
  domain: string;
  environment: string;
  criticality: Criticality;
  status: BatchStatus;
  workflowPath: string;
  workflowRef: string;
  gateRequired: boolean;
};

export const defaultBatchRegistrationValues: BatchRegistrationFormValues = {
  batchId: "",
  name: "",
  owner: "",
  domain: "",
  environment: "PROD",
  criticality: "MEDIUM",
  status: "ACTIVE",
  workflowPath: ".github/workflows/",
  workflowRef: "main",
  gateRequired: true,
};

export function toBatchDefinition(
  values: BatchRegistrationFormValues,
): BatchDefinition {
  return {
    batchId: values.batchId.trim(),
    name: values.name.trim(),
    owner: values.owner.trim(),
    domain: values.domain.trim(),
    environment: values.environment.trim(),
    criticality: values.criticality,
    status: values.status,
    workflow: {
      path: values.workflowPath.trim(),
      ref: values.workflowRef.trim(),
    },
    gateRequired: values.gateRequired,
  };
}

export function getBatchDefinitionPath(batchId: string): string {
  return `.batch-governance/batches/${batchId.trim()}.yml`;
}

export function serializeBatchDefinitionYaml(
  definition: BatchDefinition,
): string {
  return [
    "apiVersion: batchtrail.io/v1",
    "kind: BatchDefinition",
    "metadata:",
    `  id: ${yamlString(definition.batchId)}`,
    `  name: ${yamlString(definition.name)}`,
    "spec:",
    `  owner: ${yamlString(definition.owner)}`,
    `  domain: ${yamlString(definition.domain)}`,
    `  environment: ${yamlString(definition.environment)}`,
    `  criticality: ${yamlString(definition.criticality)}`,
    `  status: ${yamlString(definition.status)}`,
    "  workflow:",
    `    path: ${yamlString(definition.workflow.path)}`,
    `    ref: ${yamlString(definition.workflow.ref)}`,
    `  gateRequired: ${definition.gateRequired ? "true" : "false"}`,
    "",
  ].join("\n");
}

export function validateBatchRegistration(
  definition: BatchDefinition,
): string[] {
  const missingFields: string[] = [];

  if (!definition.batchId) missingFields.push("batchId");
  if (!definition.name) missingFields.push("name");
  if (!definition.owner) missingFields.push("owner");
  if (!definition.domain) missingFields.push("domain");
  if (!definition.environment) missingFields.push("environment");
  if (!definition.workflow.path) missingFields.push("workflow.path");
  if (!definition.workflow.ref) missingFields.push("workflow.ref");

  return missingFields;
}

export function createRegistrationBranchName(
  batchId: string,
  date = new Date(),
): string {
  const timestamp = date
    .toISOString()
    .replaceAll("-", "")
    .replaceAll(":", "")
    .replaceAll(".", "")
    .replaceAll("T", "")
    .replaceAll("Z", "")
    .slice(0, 14);
  const slug = batchId
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);

  return `batchtrail/register/${slug || "batch"}-${timestamp}`;
}

export function buildRegistrationPullRequestTitle(definition: BatchDefinition) {
  return `Register batch ${definition.batchId}`;
}

export function buildRegistrationPullRequestBody(definition: BatchDefinition) {
  return [
    "## BatchTrail Registration",
    "",
    `- Batch ID: \`${definition.batchId}\``,
    `- Name: ${definition.name}`,
    `- Environment: ${definition.environment}`,
    `- Criticality: ${definition.criticality}`,
    "",
    "This pull request was generated by BatchTrail Repo Mode.",
  ].join("\n");
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}
